# Change these first
owner: doma2k # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: mantle-1 RPC
    url: http://rpc.mantle-1.domanodes.com/
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: mantle-1 API
    url: http://api.mantle-1.domanodes.com/
    maxResponseTime: 5000
    __dangerous__insecure: true
  - name: test-mantle-1 RPC
    url: http://rpc.test-mantle-1.domanodes.com/
    maxResponseTime: 5000
    __dangerous__insecure: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://domanodes.com/.well-known/002.png
  name: Upptime
  introTitle: "**Doma🏠Nodes**"
  introMessage: "Monitoring infastructure for AssetMantle"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Doma🏠Nodes
      href: https://domanodes.com
    - title: Validator
      href: https://explorer.assetmantle.one/validators/mantlevaloper1g09pl3j043uqpw7zqkrdsxw3ve7u63efj2q0gy  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
